export const ADD_INGREDIANTS = "ADD_INGRDIANTS";
export const REMOVE_INGREDIANTS = "REMOVE_INGREDIANTS";
export const SET_INGREDIANTS = "SET_INGREDIANTS";
export const FETCH_INGREDIANT_FAILED = "FETCH_INGREDIANT_FAILED";

export const PURCHESING_BURGER_START = "PURCHESING_BURGER_START";
export const PURCHASING_SUCCESS = "PURCHASING_SUCCESS";
export const PURCHASING_FAIL = "PURCHASING_FAIL";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_STUCCESS = "AUTH_STUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
